name: AI PR Review
# Задаём имя рабочего процесса

on:
  pull_request:
    types: [opened, reopened, synchronize]
# Определяем события, на которые будет реагировать этот рабочий процесс:
# - opened: когда пулл-реквест открыт впервые
# - reopened: когда ранее закрытый пулл-реквест снова открыт
# - synchronize: когда в ветку пулл-реквеста пушится новый коммит

permissions:
  contents: read
  pull-requests: write
# Устанавливаем разрешения для работы с содержимым репозитория и пулл-реквестами:
# - contents: read разрешает чтение содержимого репозитория
# - pull-requests: write разрешает запись комментариев к пулл-реквестам

jobs:
  review:
    runs-on: ubuntu-latest
    # Определяем задачу "review", которая будет выполняться на последней версии Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Используем действие actions/checkout@v2 для клонирования репозитория
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        # Устанавливаем Python последней версии 3.10 для выполнения скрипта
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        # Обновляем pip и устанавливаем зависимость requests для Python
        
      - name: Run ChatGPT Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: ${{ secrets.OPENAI_API_ENDPOINT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODEL: ${{ secrets.MODEL }}
          SYSTEM_PROMPT: ${{ secrets.SYSTEM_PROMPT }}
          USER_PROMPT: ${{ secrets.USER_PROMPT }}

        # Передаём в окружение скрипта необходимые переменные из секретов
        run: |
          python .github/scripts/review_script.py
        # Запускаем скрипт Python для ревью кода с использованием ChatGPT
